# docker-compose.prod.yml
version: '3.8'
services:
  backend:
    image: backend
    build: .
    runtime: nvidia
    network_mode: "host"
    stdin_open: true
    tty: true
    privileged: true
    stop_signal: SIGINT
    environment:
      PATH: "/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:$PATH"
      LD_LIBRARY_PATH: "/usr/local/cuda/targets/x86_64-linux/include/:/usr/local/lib/python3.10/site-packages/nvidia/cu13/include/:$LD_LIBRARY_PATH"
      CPLUS_INCLUDE_PATH: "/usr/local/cuda/targets/x86_64-linux/include/:/usr/local/lib/python3.10/site-packages/nvidia/cu13/include/$CPLUS_INCLUDE_PATH"
      LIBRARY_PATH: "/usr/local/cuda/targets/x86_64-linux/include/:/usr/local/lib/python3.10/site-packages/nvidia/cu13/include/:$LIBRARY_PATH"
      CXX_INCLUDE_PATH: "/usr/local/cuda/targets/x86_64-linux/include/:/usr/local/lib/python3.10/site-packages/nvidia/cu13/include/:$CXX_INCLUDE_PATH"
      C_INCLUDE_PATH: "/usr/local/cuda/targets/x86_64-linux/include/:/usr/local/lib/python3.10/site-packages/nvidia/cu13/include/:$C_INCLUDE_PATH"
      NVIDIA_VISIBLE_DEVICES: all
      NVIDIA_DRIVER_CAPABILITIE: graphics
      CUDA_VISIBLE_DEVICES: "0"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - msgs-data:/app/msgs_data/
      - emb-data:/app/data/chroma/
      - $HOME/.cache/huggingface/hub:/root/.cache/huggingface/hub # Modelos pre-compilados

volumes:
  msgs-data:
    external: true
  emb-data:
    external: true