name: Check backend and frontend

on:
#  pull_request:
#    types: [opened, reopened]

  push:
    branches:
      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version: 22
        cache: 'npm'
    - run: |
        npm ci
        npm test

    - name: Generate package-lock.json, install and build the application
      working-directory: src/frontend
      run: |
        npm ci
        npm run build
    - name: Run tests
      working-directory: src/frontend
      run: npm run test