name: Check Lint and tests

on:
  pull_request:
    types: [opened, reopened]

#  push:
#    branches:
#      - master

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: python3 -m pip install -r src/backend/requirements_test.txt
    - name: Lint check with ruff
      run: |
        ruff check
        ruff format --check
    - name: Run tests with pytest
      run: pytest --full-trace -v

