name: Check backend and frontend

on:
  pull_request:
  types: [opened, reopened]

#  push:
#    branches:
#      - master

jobs:
  checks:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'
    - name: Install dependencies
      run: python3 -m pip install -r src/backend/requirements_test.txt
    - name: Lint check with ruff
      run: |
        ruff check
        ruff format --check
    - name: Run tests with pytest
      run: pytest --full-trace -v

    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        cache-dependency-path: ./src/frontend/package-lock.json
        node-version: 24.14.1
        cache: 'npm'

    - name: Install and build the application      
      run: |
        npm ci
        npm run build
      working-directory: ./src/frontend

    - name: Run tests
      run: npm run test
      working-directory: ./src/frontend